raw_data_base_dir: /Users/Beckert/devel/RenewBench-Association/testdata/raw/weather/
dst_data_base_dir: /Users/Beckert/devel/RenewBench-Association/testdata/processed/weather/healpix/
healpix_min_level: 0
healpix_max_level:
  era5: 8
  barra2_r2: 9
  barra2_c2: 11
  barra2_c2_20min: 11
  icon_dream_global: 9
  icon_dream_eu: 10
