paths:
  era5_raw_dir: /Users/Beckert/devel/RenewBench-Association/testdata/raw/weather/era5/2025/
  barra2_r2_raw_dir: /lsdf/raw/weather/barra2/R2/
  barra2_c2_raw_dir: /lsdf/raw/weather/barra2/C2/
  barra2_c2_20min_raw_dir: /lsdf/raw/weather/barra2/C2_20min/
  icon_dream_global_raw_dir: /lsdf/raw/weather/icon_dream_global/
  icon_dream_eu_raw_dir: /lsdf/raw/weather/icon_dream_eu/
  weights_cache_dir: /Users/Beckert/devel/RenewBench-Association/testdata/processed/weather/healpix/weights_cache/
  dst_zarr_store: /Users/Beckert/devel/RenewBench-Association/testdata/processed/weather/healpix/combined.zarr
healpix_min_level: 4
healpix_max_level:
  era5: 8
  barra2_r2: 9
  barra2_c2: 11
  barra2_c2_20min: 11
  icon_dream_global: 9
  icon_dream_eu: 10
